version: "2"
services:

  keycloak:
    image: wbaa/rokku-dev-keycloak:0.0.5
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080

  mariadb:
    image: wbaa/rokku-dev-mariadb:0.0.4
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3307:3306
